### ISSUE TITLE
.offers shows TUDCSE twice

### ISSUE THREAD

**Issue by AntoniosBarotsis** [martinmladenov/RankingBot#1]
Possible fix: Iterate over ``rows`` and add each offer in a new array. If the offer course already exists in the newly created array check the position and keep the higher one. Implement [here](https://github.com/martinmladenov/RankingBot/blob/622bd4a305ae4ced4f18ded5e8b8de32b25ef560/commands/offers_command.py#L38)

![image](https://user-images.githubusercontent.com/50240570/84140565-80a07780-aa5a-11ea-8cb4-f9761c547304.png)

**Comment by martinmladenov** [comment]
Thanks! Fixed in 4f528004c2c1c6a74d47af84a2de882411a76973.
