### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by martinmladenov** [martinmladenov/RankingBot#103]
To make hosting the bot easier, a Docker image containing the bot and the PostgreSQL database has to be created.

**Comment by AntoniosBarotsis** [comment]
Is the database not hosted separately already?

**Comment by martinmladenov** [comment]
The database is indeed currently hosted separately, but it will be much easier to manage if it is all contained within a single Docker container.

**Comment by AntoniosBarotsis** [comment]
I remember having a bad time trying to do that at some point with a Redis cache. I feel like this would make more sense with a compose file or with something like SQLite maybe but having them hosted separately is definitely easier.

**Comment by martinmladenov** [comment]
Docker Compose would be ideal I think.

**Comment by AntoniosBarotsis** [comment]
I'll look into it in the foreseeable future 👍

**Comment by martinmladenov** [comment]
Thanks!
