### ISSUE TITLE
Add /getrank command

### ISSUE THREAD

**Issue by martinmladenov** [martinmladenov/RankingBot#55]
Add a /getrank command to get the ranks of a specific user.
The command should not show ranks that are set as private.
Arguments:
- user
- programme (optional)
- year (optional)

**Comment by AntoniosBarotsis** [comment]
What should the `programme` argument do?

**Comment by martinmladenov** [comment]
@AntoniosBarotsis It should filter the user's ranks and show only those that are for the specified programme

**Comment by AntoniosBarotsis** [comment]
@martinmladenov What does the `user` do then? I assumed you do `/getrank @User`

**Comment by martinmladenov** [comment]
@AntoniosBarotsis each user could have multiple ranks for different programmes and years
