### ISSUE TITLE
Allow setting private status on ranks for specific programmes

### ISSUE THREAD

**Issue by martinmladenov** [martinmladenov/RankingBot#6]
Using the improvements made in #5, modify the `.toggleprivaterank` command and the corresponding service to allow users to toggle the private status on their rank for a specific programme instead of all of them (in case they have more than one rank).

New suggested usage: `.toggleprivaterank [programme_id]`

If no programme is supplied but the user only has a rank for one programme, that entry should be found and modified as there is no ambiguity.

**Comment by AntoniosBarotsis** [comment]
owo
