### ISSUE TITLE
Switch to a different framework

### ISSUE THREAD

**Issue by martinmladenov** [martinmladenov/RankingBot#91]
As discord.py may not be updated in time before the Discord API version it uses is removed, other frameworks should be looked into

**Comment by TellyO3** [comment]
Would [this](https://github.com/DisnakeDev/disnake) help?

I haven't used it myself but according to [Reddit](https://www.reddit.com/r/Discord_Bots/comments/tbrljj/comment/i0973hg/?utm_source=share&utm_medium=web2x&context=3) it is very similar.
And as you know, Reddit is always right. I could try swapping things out and see if it works. 

It seems to support commands, menu's and other modern features, and it is being updated by the looks of it.

**Comment by martinmladenov** [comment]
Closing as discord.py is supported again. See #112
